# Generated by Django 2.0.4 on 2018-05-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversario', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=50)),
                ('arbitragem', models.CharField(blank=True, max_length=80, null=True)),
                ('escudo_adversario', models.ImageField(blank=True, default='sem_escudo.png', null=True, upload_to='jogos')),
                ('placar_aldeota', models.IntegerField(blank=True, null=True)),
                ('placar_adversario', models.IntegerField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
    ]
